<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Absen_model extends CI_Model
{

    public $table = 'absen';
    public $id = 'id_absen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->order_by($this->id, $this->order);
        if ($this->session->userdata('level') == 'Siswa') {
            $id_siswa = $this->db->get('siswa', ['id_user' => $this->session->userdata('id_user') ])->row()->id_siswa;
            $this->db->where('id_siswa', $id_siswa);
        }
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->like('id_absen', $q);
        $this->db->or_like('id_siswa', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('lampiran', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_absen', $q);
        $this->db->or_like('id_siswa', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('lampiran', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Absen_model.php */
/* Location: ./application/models/Absen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-03 16:30:38 */
/* http://harviacode.com */