<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siswa_model extends CI_Model
{

    public $table = 'siswa';
    public $id = 'id_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('jurusan', 'kelas.id_jurusan=jurusan.id_jurusan', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('jurusan', 'kelas.id_jurusan=jurusan.id_jurusan', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_siswa', $q);
        $this->db->or_like('id_kelas', $q);
        $this->db->or_like('nama_siswa', $q);
        $this->db->or_like('nis', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_telepon', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('tahun_angkatan', $q);
        $this->db->from($this->table);
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('jurusan', 'kelas.id_jurusan=jurusan.id_jurusan', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_siswa', $q);
        $this->db->or_like('id_kelas', $q);
        $this->db->or_like('nama_siswa', $q);
        $this->db->or_like('nis', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_telepon', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('tahun_angkatan', $q);
        $this->db->limit($limit, $start);
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('jurusan', 'kelas.id_jurusan=jurusan.id_jurusan', 'left');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $id_user = $this->db->get_where('siswa', ['id_siswa' => $id])->row_array()['id_user'];

        $this->db->delete('user', ['id_user' => $id_user]);

        $this->db->where($this->id, $id);
        $this->db->delete($this->table);

    }

}

/* End of file Siswa_model.php */
/* Location: ./application/models/Siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-01 16:05:15 */
/* http://harviacode.com */