<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tugas_model extends CI_Model
{

    public $table = 'tugas';
    public $id = 'id_tugas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('guru', 'id_guru', 'left');
        $this->db->join('pelajaran', 'id_pelajaran', 'left');
        $this->db->order_by($this->id, $this->order);

        if ($this->session->userdata('level') == 'Guru') {
            $id_guru = $this->db->get('guru', ['id_user' => $this->session->userdata('id_user') ])->row()->id_guru;
            $this->db->where('id_guru', $id_guru);
        }

        if ($this->session->userdata('level') == 'Siswa') {
            $id_kelas = $this->db->get('siswa', ['id_user' => $this->session->userdata('id_user') ])->row()->id_kelas;
            $this->db->where('id_kelas', $id_kelas);
        }
        
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('guru', 'id_guru', 'left');
        $this->db->join('pelajaran', 'id_pelajaran', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tugas', $q);
        $this->db->or_like('id_kelas', $q);
        $this->db->or_like('id_guru', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('lampiran', $q);
        $this->db->or_like('tahun_angkatan', $q);
        $this->db->from($this->table);
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('guru', 'id_guru', 'left');
        $this->db->join('pelajaran', 'id_pelajaran', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tugas', $q);
        $this->db->or_like('id_kelas', $q);
        $this->db->or_like('id_guru', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('lampiran', $q);
        $this->db->or_like('tahun_angkatan', $q);
        $this->db->limit($limit, $start);
        $this->db->join('kelas', 'id_kelas', 'left');
        $this->db->join('guru', 'id_guru', 'left');
        $this->db->join('pelajaran', 'id_pelajaran', 'left');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tugas_model.php */
/* Location: ./application/models/Tugas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-01 16:05:43 */
/* http://harviacode.com */