<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tugas_siswa_model extends CI_Model
{

    public $table = 'tugas_siswa';
    public $id = 'id_tugas_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*,tugas_siswa.deskripsi,tugas_siswa.lampiran');
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->join('tugas', 'id_tugas', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('*,tugas_siswa.deskripsi,tugas_siswa.lampiran');
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->join('tugas', 'id_tugas', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->select('*,tugas_siswa.deskripsi,tugas_siswa.lampiran');
        $this->db->like('id_tugas_siswa', $q);
        $this->db->or_like('id_siswa', $q);
        $this->db->or_like('id_tugas', $q);
        $this->db->or_like('tugas_siswa.deskripsi', $q);
        $this->db->or_like('tugas_siswa.lampiran', $q);
        $this->db->from($this->table);
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->join('tugas', 'id_tugas', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('*,tugas_siswa.deskripsi,tugas_siswa.lampiran');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tugas_siswa', $q);
        $this->db->or_like('id_siswa', $q);
        $this->db->or_like('id_tugas', $q);
        $this->db->or_like('tugas_siswa.deskripsi', $q);
        $this->db->or_like('tugas_siswa.lampiran', $q);
        $this->db->limit($limit, $start);
        $this->db->join('siswa', 'id_siswa', 'left');
        $this->db->join('tugas', 'id_tugas', 'left');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tugas_siswa_model.php */
/* Location: ./application/models/Tugas_siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-01 16:07:00 */
/* http://harviacode.com */